### PR TITLE
solved complex relative path and base URL problems (issue #12 and #13)

### LINKED ISSUE #12: base link is being chosen wrong when the site we have ends in index.html or index.php
For instance:

http://fourcornersarts.org/index.php → http://fourcornersarts.org/index.php/about-us

but the actual base is just http://fourcornersarts.org/

### LINKED ISSUE #13: when we strip / we should strip only the first one
example: 

http://DCECENTER.COM/ → http://DCECENTER.COM/index_htmlabout-center1.html

should be /index_html/about-center1.html

(also, https://DCECENTER.com → http://DCECENTER.COMindex_htmlabout-center1.html which doesn't have the / for the base at all.)

### PR DESCRIPTION
**Pull request by jaeyk**
This is a comprehensive solution for the issue #12 and #13. 

#12 
The problem emerges when the link involves either index.html or index.php. This PR provides a simpler solution than #14. 

#13 
The problem emerges whenever the relative path has more than one depth (so the count of "/" should be equal or greater than 2). This PR resolves this issue generally (whether the depth is 2, or 2+).

### CODE REVIEW

File: R/get_about_pages.r [hunk 1]
```diff
@@ -48,7 +51,12 @@ extract_about_links <- function(base_url, timeout_thres = 10) {
   if (url.exists(base_url, timeout = timeout_thres) == FALSE) {
     stop(glue("This URL is not responding ({timeout_thres} seconds timeout)."))} 
   
-  # First, try looking for it directly
+  # If base url includes either index.php or index.html removes it 
+  if (str_detect(base_url, "index.php|index.html")) {
```
Comment (milandv) [inline R/get_about_pages.r]: there can be other patterns here as well like index.htm or home.asp. that's why i did that slightly silly thing of looking at whether the last part of the URL has a period in it.

Comment (milandv) [reply R/get_about_pages.r]: And in this case: http://www.ccunm.org/asp/home.asp  the page won't load without home.asp. The about page is at http://www.ccunm.org/ASP/aboutus.asp

Comment (jaeyk) [reply R/get_about_pages.r]: @milandv Totally makes sense. I will incorporate that part from your PR and will push a new commit.

File: R/get_about_pages.r [hunk 2]
```diff
@@ -172,12 +180,29 @@ extract_about_links <- function(base_url, timeout_thres = 10) {
         
         } else {
         
-        # FALSE (relative path)
+          # FALSE (relative path)
```
Comment (milandv) [inline R/get_about_pages.r:204]: There's one more relative path case where the path is given from the current page instead of from root. 

See about link #2 vs about link #1 here: http://milandevries.org/p3/abouttest/

File: R/get_about_pages.r (hunk 1 above)
Comment (jaeyk) [reply R/get_about_pages.r]: @milandv The new commit solves this problem to some extent but not the full. The remaining problem is `xml2::read_html()` doesn't read ASP file. Do you know how to resolve this?

File: R/get_about_pages.r (hunk 2 above)
Comment (jaeyk) [reply R/get_about_pages.r:204]: The new commit should have solved this problem. I also added #1, #2 cases as unit tests.

File: R/get_about_pages.r (hunk 1 above)
Comment (milandv) [reply R/get_about_pages.r]: i don't have a general solution but it looks like some are read and some are not, maybe?

this one seems okay: https://vfwri.org/di/vfw/v2/default.asp

Comment (milandv) [reply R/get_about_pages.r]: (In which case I think we just let it fail where it can't read them and succeed otherwise)

Comment (milandv) [reply R/get_about_pages.r]: nevermind. this works for the first one as well:

read_html(GET("http://www.ccunm.org/asp/home.asp")) %>% html_nodes("a") %>% html_attr("href")

(whereas read_html alone does not)

Comment (jaeyk) [reply R/get_about_pages.r]: @milandv I dug a little deeper ... my current impression is that it's an encoding issue. What the server sent us back is not correctly encoded. If we change the encoding to ISO-8859-1, we get the correct character vector; otherwise, it's just NA.

 Encoding Language Confidence
1 ISO-8859-1       en       0.39
2 ISO-8859-2       ro       0.16
3   UTF-16BE                0.10
4   UTF-16LE                0.10
5 ISO-8859-9       tr       0.10

Comment (jaeyk) [reply R/get_about_pages.r]: The new commit solved this encoding problem but it didn't entirely resolve the issue as the URL path doesn't form correctly. Hopefully, I will resolve this by this week.
